### ISSUE TITLE
remove global variable 'myThreshold'

### ISSUE THREAD

**Issue by hartig** [timandersson/graphql-query-calculator#2]
@shahrzadkhayatbashi I see that you introduce a global variable called `myThreshold` in [line 45](https://github.com/LiUGraphQL/graphql-result-size/blob/EarlyTermination/calculate.js#L45) and then use that global variable in some of the helper functions. That's bad coding style. Please remove this global variable and, instead, pass the threshold as an additional parameter to the functions.

**Comment by shahrzadkhayatbashi** [comment]
I addressed the global variable issue by removing it and passing it to the calculate function.

**Comment by hartig** [comment]
The fix that addresses this issue is in commit https://github.com/LiUGraphQL/graphql-result-size/commit/e3f97c65c9a179de6aa41936d49838fd13119cb4
